service: irving

plugins:
  - serverless-offline // This for testing purposes.

provider:
  name: aws
  runtime: nodejs10.x

  stage: dev
  region: sa-east-1
  memorySize: 128

functions:
  api:
    handler: build/server/main.bundle.exportServer
    events:
      - http:
          path: / # this matches the base path
          method: ANY
      - http:
          path: /{any+} # this matches any path, the token 'any' doesn't mean anything special
          method: ANY
