service: irving

# plugins:
  # - serverless-offline # Used for testing AWS Lambda locally.

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1
  memorySize: 512

package:
  exclude:
    - .git/**
    - .gitignore
    - readme.md

functions:
  app:
    handler: index.irving
    events:
      - http:
          method: GET
          path: /
      - http:
          method: GET
          path: /{any+}
