sudo: false
dist: trusty
language: node_js

node_js:
  - 10

# This "ignore" directive prevents Travis from processing branches with
# a -built suffix, thus avoiding endless loops.
if: branch =~ ^.*(?<!-built)$

branches:
  only:
    - /^travis-.*$/
    - production
    - master
    - develop
    - preprod

cache:
  directories:
    - node_modules

# Ensure npm major version matches from package.json
before_script:
  - export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
  - npm i -g npm@$(jq -r '.engines.npm' package.json | egrep -oe "[0-9]+" | head -n1)
  - npm --version

script:
  - npm run test
  - npx stylelint '{assets,client,components,styleguide}/**/*.css' --config config/stylelint.config.js
  - npm run lint
  - |
      if [ "$TRAVIS_BRANCH" == "develop" ]; then
        export API_ROOT_URL=https://technologyreview-com-develop.go-vip.net/wp-json/irving/v1
        export ROOT_URL=https://irving-technologyreview-com-develop.go-vip.net
        export ZEPHR_ROOT_URL=https://technologyreview-staging.cdn.blaize.io/
      elif [ "$TRAVIS_BRANCH" == "preprod" ]; then
        export API_ROOT_URL=https://technologyreview-com-preprod.go-vip.net/wp-json/irving/v1
        export ROOT_URL=https://irving-technologyreview-com-preprod.go-vip.net
        export ZEPHR_ROOT_URL=https://technologyreview-staging.cdn.blaize.io/
      elif [ "$TRAVIS_BRANCH" == "master" ]; then
        export API_ROOT_URL=https://technologyreview-com.go-vip.net/wp-json/irving/v1
        export ROOT_URL=https://irving-technologyreview-com.go-vip.net
        export ZEPHR_ROOT_URL=https://technologyreview-staging.cdn.blaize.io/
      fi
  - echo "Exported API_ROOT_URL $API_ROOT_URL, ROOT_URL $ROOT_URL for branch $TRAVIS_BRANCH"
  - npm install
  - npm run build

# Run the build.
# This will only happen on merges, not on PRs.
after_script:
  - bash -e bin/after-script.sh

notifications:
  email: false
