sudo: false
dist: trusty
language: node_js

node_js:
  - 10

# This "ignore" directive prevents Travis from processing branches with
# a -built suffix, thus avoiding endless loops.
if: branch =~ ^.*(?<!-built)$

branches:
  only:
    - /^travis-.*$/
    - production
    - master
    - develop
    - preprod

cache:
  directories:
    - node_modules

# Ensure npm major version matches from package.json
before_script:
  - export TRAVIS_REPO_OWNER=${TRAVIS_REPO_SLUG%/*}
  - npm i -g npm@$(jq -r '.engines.npm' package.json | egrep -oe "[0-9]+" | head -n1)
  - npm --version

script:
  - npm run test
  - npx stylelint '{assets,client,components,styleguide}/**/*.css' --config config/stylelint.config.js
  - npm run lint
  - |
      if [ "$TRAVIS_BRANCH" == "develop" ]; then
        export API_ROOT_URL=https://wp-develop.technologyreview.com/wp-json/irving/v1
        export ROOT_URL=https://irving-develop.technologyreview.com
        export ZEPHR_ROOT_URL=https://zephr-develop.technologyreview.com
        export NEXUS_ROOT_URL=https://mit-router.alley.ws
        export ONETRUST_ENABLED=1
      elif [ "$TRAVIS_BRANCH" == "preprod" ]; then
        export API_ROOT_URL=https://wp-preprod.technologyreview.com/wp-json/irving/v1
        export ROOT_URL=https://irving-preprod.technologyreview.com
        export ZEPHR_ROOT_URL=https://zephr.technologyreview.com
        export NEXUS_ROOT_URL=https://nexus.technologyreview.com
        export ONETRUST_ENABLED=1
      elif [ "$TRAVIS_BRANCH" == "master" ]; then
        export API_ROOT_URL=https://wp.technologyreview.com/wp-json/irving/v1
        export ROOT_URL=https://irving.technologyreview.com
        export ZEPHR_ROOT_URL=https://zephr.technologyreview.com
        export NEXUS_ROOT_URL=https://nexus.technologyreview.com
        export ONETRUST_ENABLED=1
      fi
  - echo "Exported API_ROOT_URL $API_ROOT_URL, ROOT_URL $ROOT_URL, ZEPHR_ROOT_URL $ZEPHR_ROOT_URL, and enabled ONETRUST for branch $TRAVIS_BRANCH"
  - npm install
  - npm run build

# Run the build.
# This will only happen on merges, not on PRs.
after_script:
  - bash -e bin/after-script.sh

notifications:
  email: false
