language: node_js

node_js:
  - 12

env:
  global:
    - API_ROOT_URL=http://live-irving.alleydev.com/wp-json/irving/v1

branches:
  only:
    - main
    - /^release\/.*$/
    
jobs:
  include: 
    - 
      if: branch = main AND type != pull_request
      script: npm run test
    - 
      if: branch = main AND type != pull_request
      script: bash bin/deploy.sh
      
notifications:
  email: false
  
# Ensure node and npm major version matches from package.json
before_install:
  - nvm install "$(jq -r '.engines.node' package.json | egrep -oe "[0-9]+" | head -n1)"
  - npm i -g npm@$(jq -r '.engines.npm' package.json | egrep -oe "[0-9]+" | head -n1)

install:
  - npm ci
  - npm run develop:bootstrap

cache:
  directories:
    - $HOME/.npm
