export const REQUEST_SUBMIT = 'REQUEST_SUBMIT';
export const RECEIVE_SUBMITTED = 'RECEIVE_SUBMITTED';
export const RECEIVE_SUBMIT_ERROR = 'RECEIVE_SUBMIT_ERROR';
export const RECEIVE_SUBMIT_INVALID = 'RECEIVE_SUBMIT_INVALID';
