module.exports = {
  name: '',
  babelConfig: [() => {}],
  componentMap: {},
  createServer: () => {},
  customizeServer: [() => {}],
  customizeDevServer: [() => {}],
  customizeProdServer: [() => {}],
  cacheService: () => {},
  debugService: () => {},
  defaultState: [() => {}],
  getAppTemplateVars: [() => {}],
  getErrorTemplateVars: [() => {}],
  monitorService: () => {},
  packages: [],
  postcssConfig: [() => {}],
  reducers: [() => {}],
  webpackConfig: [() => {}],
  sagas: [() => {}],
  serverViews: {},
  stylelintConfig: [() => {}],
};
