/* eslint-disable max-len */
// Integrations Manager.
export const HYDRATE_COMPONENTS = 'integrations/HYDRATE_COMPONENTS';
// Pico.
export const UPDATE_PICO_LIFECYCLE = 'UPDATE_PICO_LIFECYCLE';
export const PICO_CONTENT_READY = 'PICO_CONTENT_READY';
export const RECEIVE_PICO_PLAN_UPGRADE = 'RECEIVE_PICO_PLAN_UPGRADE';
export const RECEIVE_PICO_VERIFICATION_FAILURE = 'RECEIVE_PICO_VERIFICATION_FAILURE';
export const SEND_PICO_VERIFICATION_REQUEST = 'SEND_PICO_VERIFICATION_REQUEST';
export const UPDATE_PICO_PAGE_INFO = 'UPDATE_PICO_PAGE_INFO';
export const UPDATE_PICO_SIGNAL = 'UPDATE_PICO_SIGNAL';
// Coral.
export const DISMISS_CORAL_UPGRADE_MODAL = 'DISMISS_CORAL_UPGRADE_MODAL';
export const RECEIVE_CORAL_LOGIN = 'RECEIVE_CORAL_LOGIN';
export const RECEIVE_CORAL_LOGOUT = 'RECEIVE_CORAL_LOGOUT';
export const RECEIVE_CORAL_LOGOUT_REQUEST = 'RECEIVE_CORAL_LOGOUT_REQUEST';
export const RECEIVE_CORAL_SSO_TOKEN = 'RECEIVE_CORAL_SSO_TOKEN';
export const RECEIVE_CORAL_USERNAME_REQUEST = 'RECEIVE_CORAL_USERNAME_REQUEST';
export const RECEIVE_CORAL_USERNAME_SET_HASH = 'RECEIVE_CORAL_USERNAME_SET_HASH';
export const RECEIVE_CORAL_USERNAME_VALIDATION_ERROR = 'RECEIVE_CORAL_USERNAME_VALIDATION_ERROR';
export const REQUIRE_UPGRADE_FOR_CORAL_SSO = 'REQUIRE_UPGRADE_FOR_CORAL_SSO';
export const SET_CORAL_USERNAME = 'SET_CORAL_USERNAME';
export const SUBMIT_CORAL_USERNAME = 'SUBMIT_CORAL_USERNAME';
