/* eslint-disable max-len */
// Integrations Manager.
export const HYDRATE_COMPONENTS = 'integrations/HYDRATE_COMPONENTS';
// Pico.
export const PICO_LOADED = 'PICO_LOADED';
export const UPDATE_PICO_PAGE_INFO = 'UPDATE_PICO_PAGE_INFO';
export const SEND_PICO_VERIFICATION_REQUEST = 'SEND_PICO_VERIFICATION_REQUEST';
export const RECEIVE_PICO_VERIFICATION_FAILURE = 'RECEIVE_PICO_VERIFICATION_FAILURE';
export const RECEIVE_PICO_PLAN_UPGRADE = 'RECEIVE_PICO_PLAN_UPGRADE';
// Coral.
export const REQUIRE_UPGRADE_FOR_CORAL_SSO = 'REQUIRE_UPGRADE_FOR_CORAL_SSO';
export const RECEIVE_CORAL_USERNAME_REQUEST = 'RECEIVE_CORAL_USERNAME_REQUEST';
export const RECEIVE_CORAL_USERNAME_SET_HASH = 'RECEIVE_CORAL_USERNAME_SET_HASH';
export const SET_CORAL_USERNAME = 'SET_CORAL_USERNAME';
export const RECEIVE_CORAL_USERNAME_VALIDATION_ERROR = 'RECEIVE_CORAL_USERNAME_VALIDATION_ERROR';
export const RECEIVE_CORAL_SSO_TOKEN = 'RECEIVE_CORAL_SSO_TOKEN';
export const RECEIVE_CORAL_LOGOUT_REQUEST = 'RECEIVE_CORAL_LOGOUT_REQUEST';
export const RECEIVE_CORAL_LOGOUT = 'RECEIVE_CORAL_LOGOUT';
