export const LOCATION_CHANGE = 'LOCATION_CHANGE';
export const RECEIVE_COMPONENTS = 'RECEIVE_COMPONENTS';
export const RECEIVE_API_ERROR = 'RECEIVE_API_ERROR';
export const REQUEST_PAGE = 'REQUEST_PAGE';
