export const LOCATION_CHANGE = 'LOCATION_CHANGE';
export const RECEIVE_COMPONENTS = 'RECEIVE_COMPONENTS';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const FINISH_LOADING = 'FINISH_LOADING';
export const UPDATE_VISIBILITY = 'UPDATE_VISIBILITY';
export const REQUEST_SUBMIT = 'REQUEST_SUBMIT';
export const RECEIVE_SUBMITTED = 'RECEIVE_SUBMITTED';
export const RECEIVE_SUBMIT_ERROR = 'RECEIVE_SUBMIT_ERROR';
export const RECEIVE_SUBMIT_INVALID = 'RECEIVE_SUBMIT_INVALID';
export const REQUEST_COMPONENT_DATA = 'REQUEST_COMPONENT_DATA';
export const RECEIVE_COMPONENT_DATA = 'RECEIVE_COMPONENT_DATA';
export const RECEIVE_COMPONENT_DATA_ERROR = 'RECEIVE_COMPONENT_DATA_ERROR';

// Stories
export const SHOW_FULL_STORY = 'SHOW_FULL_STORY';
export const TRUNCATE_STORY = 'TRUNCATE_STORY';

// Audio player.
export const LOAD_AUDIO = 'LOAD_AUDIO';
export const PLAY_AUDIO = 'PLAY_AUDIO';
export const STOP_AUDIO = 'STOP_AUDIO';
export const PAUSE_AUDIO = 'PAUSE_AUDIO';
export const SET_AUDIO_VOLUME = 'SET_AUDIO_VOLUME';
export const SET_AUDIO_SEEK = 'SET_AUDIO_SEEK';
export const RECEIVE_AUDIO_TIME = 'RECEIVE_AUDIO_TIME';
export const LOAD_NEXT_TRACK = 'LOAD_NEXT_TRACK';
export const LOAD_PREVIOUS_TRACK = 'LOAD_PREVIOUS_TRACK';

// Header height for scroll
export const UPDATE_HEADER_HEIGHT = 'UPDATE_HEADER_HEIGHT';

// Zephr
export const REQUEST_ZEPHR_FORMS = 'REQUEST_ZEPHR_FORMS';
export const REQUEST_FORM_FOR_ROUTE = 'REQUEST_FORM_FOR_ROUTE';
export const RECEIVE_FORM_FOR_ROUTE = 'RECEIVE_FORM_FOR_ROUTE';
export const SUBMIT_ZEPHR_FORM = 'SUBMIT_ZEPHR_FORM';
export const RECEIVE_ZEPHR_USER_SESSION = 'RECIEVE_ZEPHR_USER_SESSION';
export const RECEIVE_ZEPHR_USER_PROFILE = 'RECIEVE_ZEPHR_USER_PROFILE';
export const RECEIVE_LOGIN_ERROR = 'RECEIVE_LOGIN_ERROR';

// Zephr UI
export const REQUEST_ZEPHR_UI_COMPONENTS = 'REQUEST_ZEPHR_UI_COMPONENTS';
export const RECEIVE_ZEPHR_UI_COMPONENTS = 'RECIEVE_ZEPHR_UI_COMPONENTS';
