export const LOCATION_CHANGE = 'LOCATION_CHANGE';
export const RECEIVE_COMPONENTS = 'RECEIVE_COMPONENTS';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const FINISH_LOADING = 'FINISH_LOADING';
export const UPDATE_VISIBILITY = 'UPDATE_VISIBILITY';
