export const LOCATION_CHANGE = 'LOCATION_CHANGE';
export const RECEIVE_COMPONENTS = 'RECEIVE_COMPONENTS';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';
export const FINISH_LOADING = 'FINISH_LOADING';
export const UPDATE_VISIBILITY = 'UPDATE_VISIBILITY';
export const REQUEST_SUBMIT = 'REQUEST_SUBMIT';
export const RECEIVE_SUBMITTED = 'RECEIVE_SUBMITTED';
export const RECEIVE_SUBMIT_ERROR = 'RECEIVE_SUBMIT_ERROR';
export const RECEIVE_SUBMIT_INVALID = 'RECEIVE_SUBMIT_INVALID';
export const REQUEST_COMPONENT_DATA = 'REQUEST_COMPONENT_DATA';
export const RECEIVE_COMPONENT_DATA = 'RECEIVE_COMPONENT_DATA';
export const RECEIVE_COMPONENT_DATA_ERROR = 'RECEIVE_COMPONENT_DATA_ERROR';
export const INITIATE_USER_LOGIN = 'INITIATE_USER_LOGIN';
export const RECEIVE_USER_LOGIN = 'RECEIVE_USER_LOGIN';
export const REQUEST_AUTH = 'REQUEST_AUTH';
export const RECEIVE_USER_AUTH = 'RECEIVE_USER_AUTH';
export const RECEIVE_REQUEST_HEADER = 'RECEIVE_REQUEST_HEADER';
export const SUBMIT_USER_PASSWORD = 'SUBMIT_USER_PASSWORD';
export const RECEIVE_USER_LOGOUT = 'RECEIVE_USER_LOGOUT';
export const RECEIVE_NEW_USER_EMAIL = 'RECEIVE_NEW_USER_EMAIL';
export const INITIATE_USER_REGISTRATION = 'INITIATE_USER_REGISTRATION';
export const SUBMIT_USER_REGISTRATION = 'SUBMIT_USER_REGISTRATION';
export const RECEIVE_USER_REGISTRATION = 'RECEIVE_USER_REGISTRATION';
export const VERIFY_USER_EMAIL = 'VERIFY_USER_EMAIL';

// Stories
export const SHOW_FULL_STORY = 'SHOW_FULL_STORY';
export const TRUNCATE_STORY = 'TRUNCATE_STORY';

// Audio player.
export const LOAD_AUDIO = 'LOAD_AUDIO';
export const PLAY_AUDIO = 'PLAY_AUDIO';
export const STOP_AUDIO = 'STOP_AUDIO';
export const PAUSE_AUDIO = 'PAUSE_AUDIO';
export const SET_AUDIO_VOLUME = 'SET_AUDIO_VOLUME';
export const SET_AUDIO_SEEK = 'SET_AUDIO_SEEK';
export const RECEIVE_AUDIO_TIME = 'RECEIVE_AUDIO_TIME';
export const LOAD_NEXT_TRACK = 'LOAD_NEXT_TRACK';
export const LOAD_PREVIOUS_TRACK = 'LOAD_PREVIOUS_TRACK';

// Header height for scrollup

export const GET_HEADER_HEIGHT = 'GET_HEADER_HEIGHT'; // added for getting header height for Feed Item
