# This workflow will run checks on a pull request before allowing a merge to the `main` branch.

name: Pull Request

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm run develop:bootstrap
      - run: npm test
      - run: npm audit --audit-level=high --production && npx lerna exec "npm audit --audit-level=high --production"
