on:
  push:
    branches:
      - master
      - release/**
name: Push
jobs:
  publish:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure CI Git User
        run: |
          git config --global user.email "ops+alleyci@alleyinteractive.com"
          git config --global user.name "Alley CI"
          git remote set-url origin https://$ACTOR:$TOKEN@github.com/alleyinteractive/irving
        env:
          ACTOR: ${{ secrets.ACTOR }}
          TOKEN: ${{ secrets.ALLEY_CI_TOKEN }}
      - name: Cache node_modules
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: 12.x-${{ runner.OS }}-build-${{ hashFiles('package.json') }}
      - name: Build
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: npm install
      - name: Alpha Prerelease
        env:
          GH_TOKEN: ${{ secrets.ALLEY_CI_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm run prerelease:canary:ci
