on:
  push:
    branches:
      - master
      - release/**
name: Publish on merge
jobs:
  publish:
    name: Publish to NPM
    steps:
      - name: Alpha Prerelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm run prerelease:alpha
